"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2+7#tn9klw=$suhxe0&h2f(6u3_t^u9_7ms@xs4hcy!mxv=1v3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.amazon_cognito',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1


def _load_cognito_settings():
    env_values = {
        'COGNITO_APP_CLIENT_ID': os.environ.get('COGNITO_APP_CLIENT_ID'),
        'COGNITO_APP_CLIENT_SECRET': os.environ.get('COGNITO_APP_CLIENT_SECRET'),
        'COGNITO_DOMAIN': os.environ.get('COGNITO_DOMAIN'),
    }
    if all(env_values.values()):
        return env_values
    if any(env_values.values()):
        missing = [key for key, value in env_values.items() if not value]
        raise ImproperlyConfigured(
            'Missing Cognito environment variables: ' + ', '.join(missing)
        )

    try:
        import boto3
    except ImportError as exc:
        raise ImproperlyConfigured(
            'boto3 is required to load Cognito settings from SSM.'
        ) from exc

    parameter_names = {
        'COGNITO_APP_CLIENT_ID': os.environ.get(
            'COGNITO_APP_CLIENT_ID_SSM',
            '/maosemacao/cognito/cognito_client_id',
        ),
        'COGNITO_APP_CLIENT_SECRET': os.environ.get(
            'COGNITO_APP_CLIENT_SECRET_SSM',
            '/maosemacao/cognito/cognito_client_secret',
        ),
        'COGNITO_DOMAIN': os.environ.get(
            'COGNITO_DOMAIN_SSM',
            '/maosemacao/cognito/cognito_domain',
        ),
    }
    ssm_client = boto3.client('ssm')
    response = ssm_client.get_parameters(
        Names=list(parameter_names.values()),
        WithDecryption=True,
    )
    values_by_name = {
        parameter['Name']: parameter['Value']
        for parameter in response.get('Parameters', [])
    }
    missing_parameters = [
        name for name in parameter_names.values() if name not in values_by_name
    ]
    if missing_parameters:
        raise ImproperlyConfigured(
            'Missing SSM parameters: ' + ', '.join(missing_parameters)
        )

    return {
        key: values_by_name[parameter_name]
        for key, parameter_name in parameter_names.items()
    }


_COGNITO_SETTINGS = _load_cognito_settings()

COGNITO_APP_CLIENT_ID = _COGNITO_SETTINGS['COGNITO_APP_CLIENT_ID']
COGNITO_APP_CLIENT_SECRET = _COGNITO_SETTINGS['COGNITO_APP_CLIENT_SECRET']
COGNITO_DOMAIN = _COGNITO_SETTINGS['COGNITO_DOMAIN']

SOCIALACCOUNT_PROVIDERS = {
    'amazon_cognito': {
        'APP': {
            'client_id': COGNITO_APP_CLIENT_ID,
            'secret': COGNITO_APP_CLIENT_SECRET,
            'key': '',
        },
        'DOMAIN': COGNITO_DOMAIN,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Allauth configuration
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_LOGIN_ON_GET = True

# Require email verification through Cognito/Allauth
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Adapters to disable local registration but allow Cognito registration
ACCOUNT_ADAPTER = 'core.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'core.adapters.SocialAccountAdapter'

# Redirects
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
